services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: my_postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - /d/GIS:/var/lib/postgresql/data
